Dip random
GastonGrane/JuegoPokemon pull request #42
Opened 2024-11-15 17:07 UTC by GastonGrane

2024-11-15 20:03 UTC, zugnoniguz requested changes

2024-11-15 20:03 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/NormalAttack.cs
> +    public void Use2(Pokemon target, IProbability random)
además, no sé si es pertinente que esté acá. el tema es que al ponerlo acá repetís la función use dos veces, que funciona por sobrecargado de métodos. yo capaz lo haría que sea un parámetro del ataque mismo, y que se reutilice cada vez que se ataque, logrando tener un único método Use

2024-11-15 20:03 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/NormalAttack.cs
> +        if (random.CalcularSioNo(1))
debería ser un 10%

2024-11-15 20:03 UTC, zugnoniguz commented on src/Library/GameLogic/Effects/Paralysis.cs
> -
no borres líneas al pedo

2024-11-15 20:03 UTC, zugnoniguz commented on src/Library/GameLogic/Effects/Paralysis.cs
> +        target.CanAttack = randomp.CalcularSioNo(50); // 50% probabilidad de atacar o no
lo mismo que attack

2024-11-15 20:03 UTC, zugnoniguz commented on src/Library/GameLogic/Pokemon/Pokemon.cs
> +    private bool Attack(Pokemon target, Attacks.Attack attack, IProbability random)
lo mismo que la clase attack, capaz que sea un atributo de Pokemon y no parámetro del método

2024-11-15 20:03 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/NumeroAleatorio.cs
> +    public int LimSupe;
deberían ser atributos estos? es más, si lo son deberían ser propiedades

2024-11-15 20:03 UTC, zugnoniguz commented on test/Library.Tests/FacadeTests.cs
> -namespace Library.Tests.Facade;
no borres esto

2024-11-18 22:58 UTC, zugnoniguz requested changes

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/Attack.cs
> +    /// <param name="target"> El Pokémon objetivo al que se aplicará el ataque.</param>
Un espacio de más.

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/Attack.cs
> +using Library.GameLogic.Effects;
esto no está de más?

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/NormalAttack.cs
> +using Library.GameLogic.Effects;
esto no está de más?

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Effects/Sleep.cs
> +    public Sleep(IProbability rondasdormido)
yo, si me ponés `rondasdormido`, pienso que sería un entero o algo que representa las rondas que durmió, no algo que genera rondas aleatorias

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Effects/Sleep.cs
> +    /// <param name="rondasdormido"> El tipo de aleatoriedad que queremos utilizar, para cacluclar cuantas rondas duerme.</param>
sacá el espacio.

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Effects/Sleep.cs
> +        ArgumentNullException.ThrowIfNull(rondasdormido);
ponele `ThrowIfNull(rondasdormido, nameof(rondasdormido))`

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Pokemon/Pokemon.cs
> +    public Pokemon(string name, PokemonType type, int maxHealth, List<Attack> attacks, IProbability generador)
hay manera de tipo, no repetir la lógica? es bastante quilombo no?

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/AleatoriedadPrograma.cs
> +public class AleatoriedadPrograma : IProbability
un mejor nombre porfis

2024-11-18 22:58 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/AleatoriedadPrograma.cs
> +    public bool CalcularSioNo(int porcentaje)
un mejor nombre porfis

2024-11-18 22:58 UTC, zugnoniguz commented on src/Program/Program.cs
> +            var p = new Paralysis(rand);
borrá esto

2024-11-18 22:58 UTC, zugnoniguz commented on src/Program/Program.cs
> +using Library.GameLogic.Utilities;
esto borralo

2024-11-18 23:40 UTC, zugnoniguz approved these changes

2024-11-20 21:51 UTC, zugnoniguz requested changes

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/NormalAttack.cs
> +    public virtual void Use(Pokemon target, IProbability probabilidad)
ponelo como atributo del ataque, así no tengo que repetirlo cada vez que ataque

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/SpecialAttack.cs
> +    public override void Use(Pokemon target, IProbability probabilidad)
ponelo como atributo del ataque, así no tengo que repetirlo cada vez que ataque

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/SpecialAttack.cs
> +    public override void Use(Pokemon target, IProbability probabilidad)
ya que estás, te animás a poner el check de precisión (igual que el que está en NormalAttack)? en algún momento alguien lo sacó

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Effects/Sleep.cs
> +    public Sleep(IProbability rondasaleatorias)
el nombre del parámetro debería ser más indicativo

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Pokemon/Pokemon.cs
> -    ///
dejá esto

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Pokemon/Pokemon.cs
> -    ///
dejá esto

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/IProbability.cs
> +    /// Esta logica nos da el numero de turnos que el efecto perdurara.
negativo

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/IProbability.cs
> +    /// Nos retorna el numero de turnos.
negativo

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/IProbability.cs
> +    /// Nos retorna el numero de turnos.
estás acoplando la documentación (increible) al funcionamiento del juego

2024-11-20 21:51 UTC, zugnoniguz commented on src/Library/GameLogic/Utilities/IProbability.cs
> +    /// Nos devuelve si el pokemon pudo dar un ataque critico.
lo mismo que el otro método

2024-11-24 00:35 UTC, zugnoniguz commented
En principio, me da mucha paja mergear esto

2024-11-24 00:45 UTC, GastonGrane commented
> En principio, me da mucha paja mergear esto

Eh 👁️👄👁️, me dejas un poco flipindanging

2024-11-24 19:05 UTC, zugnoniguz approved these changes

2024-11-24 19:14 UTC, merged