Comunicacion Jugador
GastonGrane/JuegoPokemon pull request #49
Opened 2024-11-17 19:26 UTC by axelher006

2024-11-17 19:26 UTC, axelher006 commented
Les cuento un poco lo que hice con el código. Básicamente, armé una clase que se encarga de guardar en cada turno lo que pasa, pero en vez de usar strings (que pueden ser más propensos a errores y difíciles de manejar), lo hago con enumeraciones, porque me pareció más limpio y seguro, además de que Guzmán me dijo que es lo mejor en estos casos jajajajajaj. Después, creé otra clase que toma esos estados y decide qué mensaje imprimir al jugador. También ajusté el juego para que esa lógica de impresión se llame automáticamente después de cada turno, así el jugador siempre sabe lo que está pasando.

Siento que con esto se cumple bastante bien lo de separar responsabilidades: una parte solo guarda estados, otra decide qué imprimir, y el resto del juego no se ensucia con detalles de impresión. Creo que está bien encaminado y que el código es escalable, pero tengo un par de dudas que me gustaría charlar con ustedes.

Primero, el tema de la calculadora de daño. Para poder mostrar cuánto daño hizo un ataque, tuve que crear una especie de cálculo directo en la clase que imprime los estados, porque no tengo una función clara a la que pueda llamar para obtener ese valor. Es un poco desprolijo, como que estoy duplicando lógica, pero no sé bien cómo resolverlo de otra forma. ¿Se les ocurre algo mejor?

Después está lo de los tests. Para poder probar la impresión, hice una conexión falsa (Fake Connection) que captura los mensajes en vez de imprimirlos realmente, y así puedo verificar qué salió. Me parece que está bien, pero no sé si es la mejor forma o si hay algo más mejor que podría hacer ahí. ¿Qué opinan ustedes?

Y lo último, el tema de que la clase Game tiene un constructor privado. Esto está bueno para controlar cómo se crean las instancias, pero me complica un montón para testear. No puedo simular partidas sin hacerlo público, y tampoco quiero romper la idea de encapsular la creación de la clase. ¿Cómo resolverían esto? ¿Hay alguna solución para que pueda usar para testear sin tocar el constructor?

2024-11-17 19:55 UTC, zugnoniguz commented
Hola Axel, hay varios temas con el código este.

En primer lugar, al hacer que la clase `CommunicationUser` sea estática, prohibís que existan dos peleas al mismo tiempo, ya que el resultado de una sobreescribrá el de la otra, y por lo tanto el "resultado" será erroneo.

Luego está el tema de que, conceptualmente, es confuso. Es un poco raro que, al atacar, tengas que hablar con alguien más para saber qué pasó. Idealmente yo querría que, si ataco, se me comunique esto como algo del método, sea el tipo de retorno o algo más, pero ahora, como ves en tus tests, no hay concordancia entre realizar una acción y lo que recibe el código que llama a esta acción, que es lo que uno esperaría.

por supuesto que se omite la efectividad de los ataques, y en caso de ser un efecto que me prohibe atacar, qué efecto me prohibe atacar, que estaría bueno comunicar.

después está el tema de GameState. primero, no es un nombre muy acorde a lo que es. sería, en teoría, algo que imprime el resultado de una acción en el juego. "ActionResultPrinter" podría ser un nombre mejor. Más allá de eso, no me convence que esta lógica tendría que ir en una clase aparte. uno podría pensar que, por ejemplo, en discord uno pondría el texto de súper crítico con algún efecto, sea negrita o algo, o en una página de html le pondría un colorsito o algo. el método PrintString es para imprimir cosas que no es razonable imprimir de otra manera, pero creo que en este caso el resultado puede ser demostrado de varias maneras, y entonces se haría como están hechos los otros métodos de la interfaz, que son métodos especializados para distintas acciones que luego realizan formateo para el servicio al cual hablan.

>Primero, el tema de la calculadora de daño. Para poder mostrar cuánto daño hizo un ataque, tuve que crear una especie de cálculo directo en la clase que imprime los estados, porque no tengo una función clara a la que pueda llamar para obtener ese valor. Es un poco desprolijo, como que estoy duplicando lógica, pero no sé bien cómo resolverlo de otra forma. ¿Se les ocurre algo mejor?
el ataque tendría que darte esta información. al atacar un pokemon, está información tendría que ser devuelta donde se llamó al ataque. tenés toda la razón que es duplicación de lógica, y justamente tendrías que ir al lugar donde ocurre esta lógica y comunicar esta información desde ahí, y no duplicar la lógica.

> Después está lo de los tests. Para poder probar la impresión, hice una conexión falsa (Fake Connection) que captura los mensajes en vez de imprimirlos realmente, y así puedo verificar qué salió. Me parece que está bien, pero no sé si es la mejor forma o si hay algo más mejor que podría hacer ahí. ¿Qué opinan ustedes?
es la manera, así se supone que se hace. es uno de los beneficios de usar dip.

>Y lo último, el tema de que la clase Game tiene un constructor privado. Esto está bueno para controlar cómo se crean las instancias, pero me complica un montón para testear. No puedo simular partidas sin hacerlo público, y tampoco quiero romper la idea de encapsular la creación de la clase. ¿Cómo resolverían esto? ¿Hay alguna solución para que pueda usar para testear sin tocar el constructor?
hay un método creategame que justamente logra esto. en teoría hay que ver el tema de la cola de jugadores y todo eso, pero en princip usarías el método CreateGame. es posible que se retire cuando implementemos la cola, pero por ahora usá ese método.

finalmente, como siempre te recuerdo, resolvé advertencias y verifica que el diff esté bien al subir un pr.

2024-11-17 23:37 UTC, axelher006 commented
Holaa, Estoy de acuerdo con casi todo lo que me mencionaste y ya estoy trabajando en ajustarlo.

Ahora, sobre lo que mencionás de que "es confuso que tengas que hablar con otra clase para saber qué pasó en un ataque". Acá lo defiendo porque quise separar responsabilidades: la acción de atacar no debería encargarse también de formatear resultados o decidir cómo comunicarlos. Devolverlo como un tipo de retorno podría simplificar algunas cosas, pero también crearía acoplamiento entre el ataque y la lógica que consume esa información. Con la implementación actual, puedo cambiar la forma de reportar los resultados sin tocar donde se lleva acabo la acción. Entiendo que conceptualmente puede ser un poco raro, pero prioricé que sea fácil de escalar si cambiamos cómo queremos mostrar o procesar los resultados (por ejemplo, mostrando un gráfico en lugar de texto). Si se vuelve más problemático que útil, lo a cambio más adelante.

2024-11-21 18:15 UTC, zugnoniguz requested changes

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/Facade/ConsoleConnection.cs
> +    public void PrintStatuses(Player attacker, Player defender, Game game)
tendría que haber un método para imprimir estado de ataque y otro de ítem

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/Facade/ConsoleConnection.cs
> +    public void PrintStatuses(Player attacker, Player defender, Game game)
y obviamente pasar solamente el estado y los jugadores, y no el game entero

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/Facade/ConsoleConnection.cs
> +                    $"¡Golpe crítico! {attacker?.ActivePokemon?.Name} atacó a {defender?.ActivePokemon?.Name}, causando {game.AttackResult.Damage} de daño. Vida restante: {defender?.ActivePokemon?.He
todas las cosas en este método tiene ? (asumen que el jugador puede ser null). obviamente no deberían, entonces se debería cambiar.

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/Facade/Game.cs
> +    public AttackResult? AttackResult { get; set; }
es un poco al pedo que game tenga el resultado del último ataque. esto debería ser pasado en el momento a la conexión externa, una vez que se necesite imprimir. aunque lo quieras guardar para después, el método en la conexión externa lo resettea

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/Facade/Game.cs
> +    public Player GetPlayerOne
si esta propiedad queda debería llamarse PlayerOne, porque no es un método, es una propiedad.

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/Facade/Game.cs
> +    public Player GetPlayerTwo
si esta propiedad queda debería llamarse PlayerTwo, porque no es un método, es una propiedad.

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/AttackResult.cs
> +public class AttackResult(AttackStatus attackStatus, int damage)
hacé una clase como la gente

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/AttackStatus.cs
> +    EffectApplied,
qué pasa si el ataque fue crítico y se le aplicó un efecto?

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/AttackStatus.cs
> +    /// Se coloca cuando no se puede usar ese ataque.
El `se coloca` está de más

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/AttackStatus.cs
> +    Empty,
no tiene nada que ver con "esperar a otro turno". además, tendría que ser un nombre más representativo, como None o algo

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/NormalAttack.cs
> +            return new AttackResult(AttackStatus.CriticalHit, criticalDamage);
esto está mal, solamente retorna el daño crítico y no el total

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Attacks/SpecialAttack.cs
> +            this.AmountUnusedTurn = 0;
repetís la lógica de disponibilidad dos veces. hay mejores formas de factorizar esto

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Items/ItemStatus.cs
> +    Empty,
el mismo comentario que el empty de attack

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Items/ItemStatus.cs
> +public enum ItemStatus
qué pasa si no se pudo usar el item?

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Items/Revive.cs
> +    public override ItemStatus Use(Pokemon? pokemon)
sacale el ?

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Players/Player.cs
> +    public AttackResult Attack(Player other, string attackName)
el attack con el índice no debería hacer lo mismo?

2024-11-21 18:15 UTC, zugnoniguz commented on src/Library/GameLogic/Pokemon/Pokemon.cs
> +        this.UpdateEffect();
esto ya no va acá

2024-11-26 02:50 UTC, zugnoniguz approved these changes

2024-11-27 01:55 UTC, zugnoniguz commented
voy a cerrar esto porque la vida a veces es demasiada corta...

2024-11-27 01:55 UTC, closed without merging